
package id.go.pajak.fasilitashibah.soa.insertfasilitashibahsoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "fasilitasPajakWp_ptt", targetNamespace = "http://soa.pajak.go.id/sca/soapservice/DjpOnline/comp_fasilitiasPajak/ws_fasilitasPajakWp")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FasilitasPajakWpPtt {


    /**
     * 
     * @param reqInsertFasilitas
     * @return
     *     returns id.go.pajak.fasilitashibah.soa.ResInsertFasilitasColl
     */
    @WebMethod(action = "insertFasilitas")
    @WebResult(name = "res_insertFasilitas", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "res_insertFasilitas")
    public ResInsertFasilitasColl insertFasilitas(
        @WebParam(name = "req_insertFasilitas", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "req_insertFasilitas")
        ReqInsertFasilitasType reqInsertFasilitas);

    /**
     * 
     * @param reqGetBpeMsg
     * @return
     *     returns id.go.pajak.fasilitashibah.soa.ResGetBpeColl
     */
    @WebMethod(action = "getBpeSuket")
    @WebResult(name = "res_getBpe", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "res_getBpe_msg")
    public ResGetBpeColl getBpeSuket(
        @WebParam(name = "req_getBpe", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "req_getBpe_msg")
        ReqGetBpeType reqGetBpeMsg);

    /**
     * 
     * @param reqMonitoringPermohonanWpMsg
     * @return
     *     returns id.go.pajak.fasilitashibah.soa.ResMonitoringPermohonanWpColl
     */
    @WebMethod(action = "monitoringPermohonanWp")
    @WebResult(name = "res_monitoringPermohonanWp", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "res_monitoringPermohonanWp_msg")
    public ResMonitoringPermohonanWpColl monitoringPermohonanWp(
        @WebParam(name = "req_monitoringPermohonanWp", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "req_monitoringPermohonanWp_msg")
        ReqMonitoringPermohonanWp reqMonitoringPermohonanWpMsg);

    /**
     * 
     * @param reqGetProdukHukumFasilitasCMMsg
     * @return
     *     returns id.go.pajak.fasilitashibah.soa.ResGetProdukHukumFasilitasCMColl
     */
    @WebMethod(action = "getProdukHukumFasilitasCM")
    @WebResult(name = "res_getProdukHukumFasilitasCM", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "res_getProdukHukumFasilitasCM_msg")
    public ResGetProdukHukumFasilitasCMColl getProdukHukumFasilitasCM(
        @WebParam(name = "req_getProdukHukumFasilitasCM", targetNamespace = "http://soa.pajak.go.id/DjpOnline/fasilitasPajak", partName = "req_getProdukHukumFasilitasCM_msg")
        ReqGetProdukHukumFasilitasCMType reqGetProdukHukumFasilitasCMMsg);

}
